apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dokba-api
  labels:
    cloud.googleapis.com/location: asia-northeast3
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cloudsql-instances: artitown:asia-northeast3:artitown-db
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 120
      serviceAccountName: dokba-api-sa@artitown.iam.gserviceaccount.com
      containers:
        - image: asia-northeast3-docker.pkg.dev/artitown/artitown-repo/dokba-api:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: GCP_PROJECT
              value: artitown
            - name: GCS_BUCKET
              value: artitown-assets
            - name: GCS_PUBLIC_URL_PREFIX
              value: https://storage.googleapis.com/artitown-assets
            - name: GUNICORN_WORKERS
              value: "2"
            - name: ALLOWED_ORIGINS
              value: https://artitown.app,https://www.artitown.app
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: latest
            - name: DOKBA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dokba-api-key
                  key: latest
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api-key
                  key: latest
          startupProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
